### ISSUE TITLE
What is missing for this to be "production ready"?

### ISSUE THREAD

**Issue by dstufft** [nir0s/ld#32]
I've just recently become aware that Python deprecated ``platform.linux_distribution()`` and plans on removing it in the future. We're using this API in pip to get information to generate statistics about what is downloading people's software. Since we still want this information we need to replace it and I saw you were working on this library but that it was marked as "WIP" and not "production ready".

So, what needs done?

**Comment by andy-maier** [comment]
Here are my two cents on this: I think it is nearly ready, but there are a few things that may end up changing the interface once they are resolved. For example, the base() method is somewhere in between just normalizing the distro ID to a defined value, and returning the distro it is based upon (like RHEL is based upon Fedora). I'll take a pass through the issues I opened and qualify them according to whether the proposed solutions would change the interface.

But Nir as the maintainer and project originator should be your main source.

**Comment by andy-maier** [comment]
I have opened issues for everything I had in mind, and have qualified them with my opinion as to whether they should be resolved before we are ready.

**Comment by nir0s** [comment]
I don't believe my view on this is better than Andy's. That being said, my intention was that users start using it so that we can get as many PRs and fixes for opened issues ASAP. Generally speaking, I'm with Andy, for the most part after fixing some of the currently opened issues we're ready to cover a large percentage of the distros and their versions.

Note that I intentionally am not going to look for bugs dealing with older versions and very very far fetched distros (i'm using Arch Linux based Antergos.. so i'm far from the plate :)) as I don't want to add code for things users might not need and will never use.

**Comment by andy-maier** [comment]
It seems to me that the remaining issues need some thinking and/or discussion.
Issue #21 breaks all RedHat distros (see Volker Braun's comment on it), and its solution is merged.

So how about releasing another version to Pypi at this point, and discuss the remaining issues next?

**Comment by nir0s** [comment]
Sounds good to me.

**Comment by andy-maier** [comment]
Hi everyone,
PR #92 is up for review and will release version 0.5.0.
That version is production-ready, from my (personal) perspective.

**Comment by andy-maier** [comment]
I just made v0.5.0 available. It is not on Pypi yet, but you can get it from the release area of this project. See here: https://github.com/nir0s/ld/releases/tag/v0.5.0

**Comment by nir0s** [comment]
0.5.0 was released to PyPI a few days ago. Congrats! :)

**Comment by nir0s** [comment]
If there are additional critical issues which you think should be solved, please open issues for each and we'll make sure we get them done before v1
