### ISSUE TITLE
regexp in _parse_release_file()

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#4]
There are multiple issues with the current regexp (r'([^0-9]+)?(?: release )?([\d+.]+)[^(]*(?:\(([\D]+)\))?'):

- Because of greedy matching, it does not strip out the "release" keyword (Ok, you strip it lateron).
- It does not allow for distro names that happen to have a digit in name (not sure such distros currently exist, but excluding that seems to be an arbitrary restriction).
- The version is restricted to contain just digits and the dot. Anything after the so defined version is dropped. E.g. suffixes with letters (e.g. "rc", "dev", "a") are dropped, or the hyphen.
- The regexp does not allow for digits in the codename. Again, that seems to be an arbitrary restriction.

In addition, the current code does not handle the case where the regexp does not match.

Overall, the greedy matching makes it nearly impossible to come up with a regexp that resolves these issues, without introducing arbitrary restrictions. Parsing the reverse string gets greedy matching to work in the right direction:

        _release_version = re.compile(
            r'(?:\)(.*)\()? *([\d.+\-a-z]*\d) *(?:esaeler *)?(.+)')
        m = _release_version.match(content[::-1])
        if not m:
            name = version = codename = ''
            # TODO: Maybe improve this way of handling non-matching
        else:
            name = m.group(3)[::-1]   # regexp ensures it is non-None
            version = m.group(2)[::-1]   # regexp ensures it is non-None
            codename = (m.group(1) or '')[::-1]   # may be None
        props = {
            'name': name,
            'version_id': version
            'codename': codename
        }
        return props

**Comment by nir0s** [comment]
I wanted to be as restrictive as possible as I think making this to permissive can cause much harm.. but you've got me thinking this over and i'm implementing this.
One problem that I have with this, though, is codename. Take OpenSUSE for example, its first line in  /etc/SuSE-release in 42.1 is simply: "openSUSE 42.1 (x86_64)". x86_64 it not a codename. We can document that we're not responsible for weird things that come from non-standardized codenaming in release files.. or we can (since i'm not familiar with any distribution which has digits in its codenames), not allow this and if we ever stumble into such a situation, we'll modify the code.
We can also specifically restrict this when on openSUSE (as per what I intend to do in `_set_distribution_properties`)

What do you think?

**Comment by nir0s** [comment]
Anyhow,  https://github.com/nir0s/ld/tree/various-fixes-and-optimizations contains the modified code for now. We should think this through, but I guess your solution is clearer.

**Comment by nir0s** [comment]
solved in 0.2.0
