### ISSUE TITLE
Discussion: Interface changes before 1.0.0?

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#72]
Before the external interface is nailed down in a 1.0.0 version, I'd like to bring up the following thoughts for possible changes. Please comment on them in this issue here.

1. We could move the content of `ld/constants.py` into `ld/__init__.py`. The externally visible part of the `ld.constants` sub-module defines three translation tables for the normalization of distro IDs. That somehow seems too small to warrant its own sub-module.

2. Naming inconsistency of the `get_*_release_attr()` functions. They are the only ones with a `get_` prefix. The `*_release_info()` functions, as well as the functions to retrieve the single information items such as `name()` do not have such a prefix. We could remove the `get_` prefix from the `get_*_release_attr()` functions and methods.

3. Version returned in `info()`: Its result currently includes the first version found. We could change it to include the best version found, instead (see `best` parameter of `version()`).

More??

**Comment by nir0s** [comment]
1. I would definitely consolidate the two. On top of that, I would also suggest to remove the "ld" package and make this a single module. Not sure why we need a package.

2. Agreed.

3. Commented on the other issue related to this.

4. #101

**Comment by nir0s** [comment]
#102:

* Introduces the consolidation of `constants.py`
* Removes the `ld` package in favor of the `ld.py` module.
* Add an additional class for attributes only allowing to run `ld.name` instead of `ld.name()`, etc.. these don't cover everything and we need to come up with a way to deprecate other functions if we decide to do so.
* Breaking the `LinuxDistribution()` class API. The new `LinuxDistribution()` class is now saved for attributes.

To use attributes, you will need to `from ld import ld` instead of just `import ld`.

Before continuing with testing, documentation, etc.. I'd like to ask for comments regarding whether the attributes thing is at all necessary.

**Comment by andy-maier** [comment]
On attributes: There are undoubtedly situations in which one wants to access attributes that are not in the set of common attributes for which we have specific functions. For example, typical os-release files have several of them, and even lsb_release has the LSB conformance information. The only question to me is how we provide access to them. Currently, we have two ways:

* Get all attributes of a particular data source via `<src>_release_info()`.
* Get a single named attribute of a particular data source via `get_<src>_release_attr()`, with the usual default mechanism if not found.

The support for a default is only available through the `get_<src>_release_attr()` functions. Second, it seems natural to me to be able to have a function to retrieve a single attribute if that's all you need.

I think I lean towards keeping the attribute retrieval functions.

**Comment by nir0s** [comment]
I've merged #102 dealing with removing the package in favor a module and consolidating constant.py.

**Comment by andy-maier** [comment]
ok.

**Comment by nir0s** [comment]
#111 removes the `get_` prefix.

**Comment by andy-maier** [comment]
That addresses this issue completely. I'll close it.
