### ISSUE TITLE
Should info() use first or best version for its version-related results?

### ISSUE THREAD

**Issue by andy-maier** [nir0s/ld#94]
Currently, in its result, the `info()` method provides the first available version of the (possibly multiple) underlying data sources (i.e. specify argument `best=False`).

It would be possible to use the version with the best precision, instead (i.e. specify argument `best=True`).

Please provide your review/considerations/wishes about which way to go in this matter, by commenting on this issue.

**Comment by nir0s** [comment]
My problem with "best" is that it's potentially inconsistent. While it is useless in many cases, it also poses a problem. I'd rather depend solely on a single source which is provided as a standard (i.e. VERSION_ID) and let the user decide whether they want to explicitly retrieve the "best" version. Another option would be to expose arguments in `info` which would allow a user to pass `best=True`, `pretty=True`, etc..

**Comment by andy-maier** [comment]
You mean, inconsistent w.r.t the data source, i.e. the best version can come from a different data source than say, the ID?

That can be the case for some other attributes as well: For example, it is possible that a distro has both a distro release file and an os-release file, and that the codename comes from the distro release file (because os-release files do not have an attribute for that, and not every distro puts the code name into the VERSION field) and the ID comes from the os-release file because it has precedence over the distro release file.

In addition to adding `best` and `pretty` arguments to `info()`, we could also add more fields inside the returned data. Which has some similarity to introducing properties, in a way.

**Comment by nir0s** [comment]
I believe the problem with Codename is more that it, itself, is inconsistent throughout the difference distributions while version is not. To answer your question, yes, `best` version is "potentially" inconsistent due to the different data sources and is less explicit in the sense that when a user asks for the version, they might expect to get what's in os-release's VERSION_ID field specifically and not anywhere else.

I suggest we add best and pretty in info which will both be false by default and allow the user to decide rather than force it upon them.

As for the future, as we assume os-release will be the standard for most distros (don't we?), `best` might be dropped in which case people will start getting the "non-best" version just because the "best" version which was deprecated when they removed the distro specific file (for instance) is removed.

**Comment by andy-maier** [comment]
ok.

**Comment by nir0s** [comment]
Should we close this issue? :)

**Comment by andy-maier** [comment]
I'd like to provide a PR that adds a `best` parameter to `info()`.
I'm not sure about adding `pretty`, because `info()` is described as providing machine-readable information, which is not really consistent with providing prettified data.

**Comment by andy-maier** [comment]
Addressed that in PR #113.
